name: Auto Close Inactive Tickets

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  close_tickets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Calculate epoch date threshold
        id: calculate_epoch_date
        run: echo "$(date -u -d '15 days ago' +%s)" >> epoch_date.txt

      - name: Debug - Show epoch date threshold
        run: cat epoch_date.txt

      - name: List all open issues older than 15 days
        id: list_old_issues
        run: |
          echo "Listing issues older than 15 days..."
          threshold_date="$(date -u -d '15 days ago' --iso-8601=seconds)"
          echo "Threshold date: $threshold_date"

          older_than_15_days_json=$(curl -s -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues?q=updated:<$threshold_date")
          echo "$older_than_15_days_json" >> older_than_15_days.json

          if [[ $(jq length older_than_15_days.json) -eq 0 ]]; then
            echo "No issues older than 15 days found."
          else
            echo "Found issues older than 15 days:"
            cat older_than_15_days.json
          fi

      - name: Fetch labels for issues
        run: |
          for issue_number in $(jq -r '.[].number' older_than_15_days.json); do
            echo "Fetching labels for issue $issue_number..."
            labels_json=$(curl -s -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/labels")
            echo "$labels_json" > labels_$issue_number.json

            # Check if the issue has the 'need more info' label
            if jq -e '.[].name | contains("need more info")' < labels_$issue_number.json >/dev/null; then
              echo "Issue $issue_number has 'need more info' label."
              echo "Adding a comment to issue $issue_number"
              curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" -d '{"body": "This issue was closed due to inactivity."}' "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/comments"
              echo "Closing issue $issue_number"
              curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" -d '{"state": "closed"}' "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
            else
              echo "Issue $issue_number does not have 'need more info' label."
            fi
          done
